### ISSUE TITLE
foreach missing in package.json

### ISSUE THREAD

**Issue by matthewmueller** [ashaffer/virtex-dom#1]
https://github.com/ashaffer/virtex-dom/blob/932b57db2596f658ed47e5b438ce9ee76968b040/src/createElement.js#L6

**Comment by ashaffer** [comment]
Apologies again. Fixed. I'm testing a clean install myself now, so hopefully will catch any more of these.

**Comment by ashaffer** [comment]
@matthewmueller Alright got a clean test install working! Hopefully no more of these kinds of issues.
